name: Tailscale exit node

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

concurrency:
  group: tailscale-exit-node
  cancel-in-progress: true

jobs:
  run-tailscale-exit-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable IP forwarding
        run: |
          echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf
          echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf
          sudo sysctl -p /etc/sysctl.d/99-tailscale.conf

      - name: Start Tailscale Exit Node
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          args: "--advertise-exit-node --hostname us-azure-node"

      - name: Keep Runner Alive
        run: |
          echo 
          echo "Tailscale exit node is active, will remain active for approximately 6 hours."
          sleep 21540
